name: CI

on: push

env:
  GITHUB_REPO: smack0007/snow-shovel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deno Setup
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.27.0"

      - name: Test
        run: |
          deno test